variables:
  IMAGE: $REGISTRY_HOST/stack/auth-proxy

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build-master:
  tags: [shell]
  script:
    - docker build -t $IMAGE:latest .
    - docker push $IMAGE:latest

build-tag:
  tags: [shell]
  script:
    - docker build -t $IMAGE:$CI_BUILD_TAG .
    - docker push $IMAGE:$CI_BUILD_TAG
  only:
    - tags
